EmployeeManagement/Controllers/ChatController.cs
using EmployeeManagement.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeManagement.Controllers
{
    public class ChatController : Controller
    {
        private EmployeeDbContext _dbContext = new EmployeeDbContext();
        // GET: Chat
        public ActionResult Index()
        {
            if (Session["IsAdmin"] == null)
                return RedirectToAction("Login", "Account");

            var EmployeeId = Session["EmployeeId"].ToString();
            var AllEmployees = _dbContext.Employees.Where(x=>x.Id != EmployeeId).ToList();
            ViewBag.Employees = AllEmployees;
            return View();
        }
    }
}

EmployeeManagement/Controllers/LeaveController.cs
using EmployeeManagement.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeManagement.Controllers
{
    public class LeaveController : Controller
    {
        private EmployeeDbContext _dbContext = new EmployeeDbContext();
        // GET: Leave
        public ActionResult AddLeaveRequest()
        {
            if (Session["IsAdmin"] == null)
                return RedirectToAction("Login", "Account");
            var CurrentDate = DateTime.Now.ToString("yyyy-MM-dd");
            ViewBag.CurrentDate = CurrentDate;
            return View();
        }

        public ActionResult ViewLeaveRequest()
        {
            if (Session["IsAdmin"] == null)
                return RedirectToAction("Login", "Account");

            var CurrentDate = DateTime.Now.ToString("yyyy-MM");
            ViewBag.CurrentDate = CurrentDate;
            return View();
        }

        public ActionResult ViewPendingRequest()
        {
            if (Session["IsAdmin"] == null)
                return RedirectToAction("Login", "Account");

            var IsAdmin = (int)Session["IsAdmin"];
            var EmployeeId = Session["EmployeeId"].ToString();
            List<LeaveRequest> LeaveRequestList = new List<LeaveRequest>();

            var Listitems = (from lr in _dbContext.LeaveRequest
                             join emp in _dbContext.Employees on lr.EmployeeId equals emp.Id
                             where lr.Status.ToLower() == "pending"
                             && (IsAdmin == 0 ? lr.EmployeeId == EmployeeId : true)
                             select new Object.LeaveRequestInfo
                             {
                                 Id = lr.Id,
                                 EmployeeId = emp.Id,
                                 EmployeeCode = emp.EmployeeCode,
                                 Name = emp.Name,
                                 Team = emp.Team,
                                 Title = lr.Title,
                                 Description = lr.Description,
                                 FromDate = lr.FromDate,
                                 ToDate = lr.ToDate,
                                 Comments = lr.Comments
                             }).ToList();
            
            ViewBag.LeaveRequest = Listitems;
            return View();
        }
    }
}

EmployeeManagement/Controllers/NewsController.cs
using EmployeeManagement.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeManagement.Controllers
{
    public class NewsController : Controller
    {
        private EmployeeDbContext _dbContext = new EmployeeDbContext();
        // GET: New
        public ActionResult AddNews()
        {
            if (Session["IsAdmin"] == null)
                return RedirectToAction("Login", "Account");

            var EmployeesList = _dbContext.Employees.ToList();
            ViewBag.EmployeesList = EmployeesList;
            return View();
        }

        public ActionResult ListNews()
        {
            if (Session["IsAdmin"] == null)
                return RedirectToAction("Login", "Account");

            List<News> NewsList = new List<News>();
            if(Session["IsAdmin"].ToString() == "1")
            {
                NewsList = _dbContext.News.ToList();
            }
            else
            {
                string EmployeeId = Session["EmployeeId"].ToString();
                NewsList = (from ns in _dbContext.News
                            join nc in _dbContext.NewsConnector on ns.Id equals nc.NewsId
                            where nc.EmployeeId == EmployeeId
                            select ns).ToList();
            }
            ViewBag.NewsList = NewsList;
            return View();
        }
    }
}

EmployeeManagement/Controllers/PaySlipController.cs
using EmployeeManagement.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace EmployeeManagement.Controllers
{
    public class PaySlipController : Controller
    {
        private EmployeeDbContext _dbContext = new EmployeeDbContext();
        // GET: PaySlip
        public ActionResult AddPaySlip()
        {
            if (Session["IsAdmin"] == null)
                return RedirectToAction("Login", "Account");

            var EmployeesList = _dbContext.Employees.ToList();
            ViewBag.EmployeesList = EmployeesList;
            var CurrentDate = DateTime.Now.ToString("yyyy-MM");
            ViewBag.CurrentDate = CurrentDate;
            return View();
        }

        public ActionResult ViewSlip()
        {
            if (Session["IsAdmin"] == null)
                return RedirectToAction("Login", "Account");

            if(Session["IsAdmin"].ToString() == "1")
            {
                var EmployeesList = _dbContext.Employees.ToList();
                ViewBag.EmployeesList = EmployeesList;
                var CurrentDate = DateTime.Now.ToString("yyyy-MM");
                ViewBag.CurrentDate = CurrentDate;
                ViewBag.MinimumDate = "1900-01";
            }
            else
            {
                string EmployeeId = Session["EmployeeId"].ToString();
                var EmployeeInfo = _dbContext.Employees.Where(x=>x.Id == EmployeeId).FirstOrDefault();
                if(EmployeeInfo != null && !string.IsNullOrEmpty(EmployeeInfo.Id))
                {
                    var MinimumDate = EmployeeInfo.DOJ.ToString("yyyy-MM");
                    ViewBag.MinimumDate = MinimumDate;
                }
            }

            
            return View();
        }
    }
}

EmployeeManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport">
    <title>Kavitha Technologies</title>

    <!-- General CSS Files -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">

    <!-- Template CSS -->
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="stylesheet" href="~/assets/css/components.css">
    <link rel="stylesheet" href="~/App_Assests/css/custom.css">
    <link rel="stylesheet" href="https://www.jqueryscript.net/demo/jQuery-Plugin-For-Built-In-Loading-Indicator-In-Buttons-Button-Loader/buttonLoader.css"">
</head>

<body>
    <div id="app">
        <div class="main-wrapper">
            <div class="navbar-bg"></div>
            <nav class="navbar navbar-expand-lg main-navbar">
                <form class="form-inline mr-auto">
                    <ul class="navbar-nav mr-3">
                        <li><a href="javascript:void(0);" data-toggle="sidebar" class="nav-link nav-link-lg"><i class="fas fa-bars"></i></a></li>
                    </ul>
                </form>
                <ul class="navbar-nav navbar-right">
                    <li class="dropdown">
                        <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle nav-link-lg nav-link-user">
                            <img alt="image" src="@Session["ProfileImage"].ToString()" class="rounded-circle mr-1 Profileimage">
                            <div class="d-sm-none d-lg-inline-block"><span class="EmployeeName">@Session["Name"].ToString()</span></div>
                        </a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a href="@Url.Action("Profile", "Account")" class="dropdown-item has-icon">
                                <i class="far fa-user"></i> Profile
                            </a>
                            <a href="@Url.Action("ChangePassword", "Account")" class="dropdown-item has-icon">
                                <i class="far fa-user"></i> Change Password
                            </a>
                            <div class="dropdown-divider"></div>
                            <a href="@Url.Action("Login", "Account")" class="dropdown-item has-icon text-danger">
                                <i class="fas fa-sign-out-alt"></i> Logout
                            </a>
                        </div>
                    </li>
                </ul>
            </nav>
            <div class="main-sidebar">
                <aside id="sidebar-wrapper">
                    <div class="sidebar-brand">
                        <a href="@Url.Action("index", "Dashboard")">Tech</a>
                    </div>
                    <div class="sidebar-brand sidebar-brand-sm">
                        <a href="index.html">Tech</a>
                    </div>
                    @if (Session["IsAdmin"].ToString() == "1")
                    {
                        <ul class="sidebar-menu">
                            <li class="menu-header text-info">DashBoard</li>
                            <li id="dashboard"><a class="nav-link" href="@Url.Action("index", "Dashboard")"> <i class="fas fa-fire"></i><span>DashBoard</span></a></li>

                            <li class="menu-header text-info">Employee Management</li>
                            <li id="addEmployee"><a class="nav-link" href="@Url.Action("AddEmployee", "Employee")" id="AddUserPage"><i class="fas fa-solid fa-user"></i><span>Add Employee</span></a></li>
                            <li id="viewEmployee"><a class="nav-link" href="@Url.Action("ListEmployee", "Employee")" id="ViewUserPage"><i class="fas fa-solid fa-users"></i><span>All Employees</span></a></li>

                            <li class="menu-header text-info">Leave Request</li>
                            <li id="viewPendingRequest"><a class="nav-link" href="@Url.Action("ViewPendingRequest", "Leave")" id="AddUserPage"><i class="fas fa-solid fa-list-ul"></i><span>View Pending Request</span></a></li>

                            <li id="viewLeaveRequest"><a class="nav-link" href="@Url.Action("ViewLeaveRequest", "Leave")" id="AddUserPage"><i class="fas fa-solid fa-list-ul"></i><span>View All Requests</span></a></li>

                            <li class="menu-header text-info">Pay Slip</li>
                            <li id="addPaySlip"><a class="nav-link" href="@Url.Action("AddPaySlip", "PaySlip")" id="AddUserPage"><i class="fas fa-solid fa-credit-card"></i><span>Add PaySlip</span></a></li>
                            <li id="viewPaySlip"><a class="nav-link" href="@Url.Action("ViewSlip", "PaySlip")" id="AddUserPage"><i class="fas fa-solid fa-credit-card"></i><span>View PaySlip</span></a></li>

                            <li class="menu-header text-info">News</li>
                            <li id="addNews"><a class="nav-link" href="@Url.Action("AddNews", "News")" id="AddUserPage"><i class="fas fa-regular fa-newspaper"></i><span>Add News</span></a></li>
                            <li id="viewNews"><a class="nav-link" href="@Url.Action("ListNews", "News")" id="AddUserPage"><i class="fas fa-regular fa-folder-open"></i><span>View News</span></a></li>

                            <li class="menu-header text-info">Chat</li>
                            <li id="chatting"><a class="nav-link" href="@Url.Action("Index", "Chat")" id="AddUserPage"><i class="fas fa-solid fa-comment"></i><span>Chat</span></a></li>

                        </ul> }
                    else
                    {
                        <ul class="sidebar-menu">
                            <li class="menu-header text-info">DashBoard</li>
                            <li id="dashboard"><a class="nav-link" href="@Url.Action("index", "Dashboard")"> <i class="fas fa-fire"></i><span>DashBoard</span></a></li>

                            <li class="menu-header text-info">Leave Request</li>
                            <li id="addLeaveRequest"><a class="nav-link" href="@Url.Action("AddLeaveRequest", "Leave")" id="AddUserPage"><i class="fas fa-solid fa-list-ul"></i><span>Add Leave Request</span></a></li>
                            <li id="viewPendingRequest"><a class="nav-link" href="@Url.Action("ViewPendingRequest", "Leave")" id="AddUserPage"><i class="fas fa-solid fa-list-ul"></i><span>View Pending Request</span></a></li>
                            <li id="viewLeaveRequest"><a class="nav-link" href="@Url.Action("ViewLeaveRequest", "Leave")" id="AddUserPage"><i class="fas fa-solid fa-list-ul"></i><span>View All Requests</span></a></li>

                            <li class="menu-header text-info">Pay Slip</li>
                            <li id="viewPaySlip"><a class="nav-link" href="@Url.Action("ViewSlip", "PaySlip")" id="AddUserPage"><i class="fas fa-solid fa-credit-card"></i><span>View PaySlip</span></a></li>

                            <li class="menu-header text-info">News</li>
                            <li id="viewNews"><a class="nav-link" href="@Url.Action("ListNews", "News")" id="AddUserPage"><i class="fas fa-regular fa-folder-open"></i><span>View News</span></a></li>

                            <li class="menu-header text-info">Chat</li>
                            <li id="chatting"><a class="nav-link" href="@Url.Action("Index", "Chat")" id="AddUserPage"><i class="fas fa-solid fa-comment"></i><span>Chat</span></a></li>

                        </ul>}
                </aside>
            </div>

            <!-- Main Content -->
            <div class="main-content">
                @RenderBody()
            </div>
            <footer class="main-footer">
            </footer>
        </div>
    </div>

    <!-- General JS Scripts -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.nicescroll/3.7.6/jquery.nicescroll.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.24.0/moment.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://www.jqueryscript.net/demo/jQuery-Plugin-For-Built-In-Loading-Indicator-In-Buttons-Button-Loader/jquery.buttonLoader.js"></script>

    <script src="~/assets/js/stisla.js"></script>

    <!-- Template JS File -->
    <script src="~/assets/js/scripts.js"></script>
    <script src="~/App_Assests/js/custom.js"></script>

    <!-- Page Specific JS File -->
    <script src="~/assets/js/page/index.js"></script>

    <script>
        $(document).ready(function () {
            var URL = window.location.pathname;
            switch (URL) {
                case "/Dashboard/index":
                    $("#dashboard").addClass("active");
                    break;
                case "/Employee/AddEmployee":
                    $("#addEmployee").addClass("active");
                    break;
                case "/Employee/ListEmployee":
                    $("#viewEmployee").addClass("active");
                    break;
                case "/Leave/ViewLeaveRequest":
                    $("#viewLeaveRequest").addClass("active");
                    break;
                case "/Leave/AddLeaveRequest":
                    $("#addLeaveRequest").addClass("active");
                    break;
                case "/Leave/ViewPendingRequest":
                    $("#viewPendingRequest").addClass("active");
                    break;
                case "/PaySlip/AddPaySlip":
                    $("#addPaySlip").addClass("active");
                    break;
                case "/PaySlip/ViewSlip":
                    $("#viewPaySlip").addClass("active");
                    break;
                case "/News/AddNews":
                    var myDiv = $("div.main-sidebar")[0];
                    myDiv.scrollTop = myDiv.scrollHeight;
                    $("#addNews").addClass("active");
                    break;
                case "/News/ListNews":
                    var myDiv = $("div.main-sidebar")[0];
                    myDiv.scrollTop = myDiv.scrollHeight;
                    $("#viewNews").addClass("active");
                    break;
                case "/Chat/Index":
                    var myDiv = $("div.main-sidebar")[0];
                    myDiv.scrollTop = myDiv.scrollHeight;
                    $("#chatting").addClass("active");
                    break;
            }
        });
    </script>
</body>
</html>